### ISSUE TITLE
Align waveform bars to center

### ISSUE THREAD

**Issue by MSOB7YY** [ryanheise/just_waveform#27]
the waveform bars are not vertically centered, how to achieve that?
![Screenshot 2022-12-23 015531](https://user-images.githubusercontent.com/85245079/209244756-80596b7c-ed18-48de-8769-aa594a96d4cf.png)

**Comment by ryanheise** [comment]
This plugin just extracts the raw waveform data (at a lower resolution), and the fact is, raw waveform data looks like that. If you want to display something more fake to make it look the way you want, it's not hard for you to come up with something, since the example app already shows one example of how you can render these bars. For example, every bar has a min and max value. If you ignored the min value and just used -max instead, then max and -max would both have a symmetrical distance from the origin. Another idea is that you could take the distance between min and max and halve it, then instead of graphing from min to max, you could graph from distance to -distance.

etc. etc. But the purpose of this plugin is just to provide you with the raw data which you can display however you like, it is really up to you to do the rest.
