### ISSUE TITLE
Draw waveform on audio record

### ISSUE THREAD

**Issue by subzero911** [ryanheise/just_waveform#4]
request

**Comment by ryanheise** [comment]
You need a different package depending on where you read the waveform data from:

1. If you want to draw a waveform while audio is playing, you need that feature supported by your audio player package so that you can read the wave data live.
2. If you want to draw a waveform while audio is recording, you need that feature supported by your audio recorder package so that you can read wave data live.
3. If you want to draw a waveform from an audio file, then you need a package to provide waveform data from a file source (i.e. this package).

For 1, just_audio supports this on the `visualizer` branch.
For 2, a quick search reveals [mic_stream](https://pub.dev/packages/mic_stream)
For 3, try just_waveform.

**Comment by subzero911** [comment]
I want (2) - to draw wave data live while audio is recording

**Comment by ryanheise** [comment]
You missed below that because I answered already:

> For 2, a quick search reveals [mic_stream](https://pub.dev/packages/mic_stream)

**Comment by subzero911** [comment]
But how can stream from the microphone help me to draw it?
just_waveform can draw only from file, not from stream.

**Comment by ryanheise** [comment]
No, just_waveform does not draw anything. What gave you that idea? I also said you need a different package. I thought my previous answer was pretty clear, so can you read it again? It is clear that you need a different package isn't it?

**Comment by subzero911** [comment]
Okay, I see now.
just_waveform extracts stream from the audio file
And just_audio can draw it as a waveform, right?

**Comment by ryanheise** [comment]
> just_waveform extracts stream from the audio file

Yes.

> And just_audio can draw it as a waveform, right?

No. just_audio is an audio player. It doesn't draw anything. You are making the same assumption again that a certain package draws something. All 3 types of packages in my list above provide access to audio data but from 3 different sources. It is up to you to draw it yourself.

I will close this issue since at the moment you are no longer asking about something that my package is responsible for.
